version: "3.8"
services:
  laravel_app:
    container_name: laravel_app
    extra_hosts:
     - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
       - '${APP_PORT:-80}:80'
       - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    expose:
      - 9000
    volumes:
      - .:/var/www/html
    depends_on:
      - laravel_db
    networks:
      - laravel_network

  laravel_nginx:
    container_name: laravel_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
    depends_on:
      - laravel_app
    networks:
      - laravel_network

  laravel_db:
    container_name: laravel_db
    image: 'postgres:13'
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'storepgsql:/var/lib/postgresql/data'
    networks:
      - laravel_network

  laravel_redis:
    container_name: laravel_redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
       - 'storeredis:/data'
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  storepgsql:
    driver: local
  storeredis:
    driver: local
